# Generated by Django 2.2.3 on 2019-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20190806_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='image',
            new_name='mg_url',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolution_to',
            new_name='next_evolution',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name_jp',
            new_name='title_jp',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='name',
            new_name='title_ru',
        ),
    ]
