# Generated by Django 2.2.3 on 2019-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_auto_20190806_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='mg_url',
            new_name='img_url',
        ),
    ]
