# Generated by Django 2.2.3 on 2019-08-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20190806_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='next_evolution',
            new_name='evolution_from',
        ),
    ]
