# Generated by Django 2.2.3 on 2019-08-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20190808_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img_url',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
